sudo: required

language: go

go:
  - "1.10.3"

branches:
  only:
  - code

env:
  global:
  - SSH_KEY="coffeenet_release_dude"
  - GIT_NAME="CoffeeNet Release Dude"
  - GIT_EMAIL="coffeenet@Tobsch.org"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="code"

before_install:
  - openssl aes-256-cbc -K $encrypted_113f435026cc_key -iv $encrypted_113f435026cc_iv -in coffeenet_release_dude.enc -out coffeenet_release_dude -d

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

before_script:
  - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2

script:
  - "./scripts/downloader"
  - hugo

after_success:
  - git submodule init
  - echo "coffeenet.rocks" > ./public/CNAME
  - chmod a+x ./scripts/deploy.sh
  - "./scripts/deploy.sh"
