baseURL = "https://coffeenet.rocks/"
languageCode = "en-us"
title = "CoffeeNet"
theme = "coffeenet"

[outputs]
  page = ["html","json"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffix = "json"
[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"