name = "CoffeeNet"
description = "Homepage theme of the CoffeeNet"
homepage = "https://coffeenet.rocks/"
tags = []
features = []
min_version = "0.43"

[author]
  name = "Tobias Schneider"
  homepage = "http://coffeenet.rocks/"
