name = "CoffeeNet"
description = "Homepage theme of the CoffeeNet"
homepage = "http://coffeenet.rocks/"
tags = []
features = []
min_version = "0.38"

[author]
  name = "Tobias Schneider"
  homepage = "http://coffeenet.rocks/"
